#!/usr/bin/env python
# -*- coding:utf-8 -*-

################################################################
# file name:    gen_TOC.py
# author:       zdz
# date:         2016.10.15
# brief:        generate a TOC for .md file in github
################################################################

import sys
import time
import shutil
import re

LINK=r"(TOC generated by [github_markdown_toc](https://github.com/zhangdanzhu/github_markdown_toc))" + "\n\n"

def process_headings(heading):
	# remove ^#+\s*
	i = 0
	n = 0   #number of #
	while ('#' == heading[i]):
		n += 1
		i += 1
	new_heading = re.sub(r"^#+\s*", '', heading)
	new_heading = re.sub(r"\[", r"\\[", new_heading)
	new_heading = re.sub(r"\]", r"\\]", new_heading)
	heading = re.sub(r"[\\\~\`\!\@\#\$\%\^\&\*\(\)\_\+\=\|\{\}\[\]\?\>\<,\./\'\:\;\"]", '', new_heading)
	heading = re.sub("～|！|￥|…|×|（|）|—|？|《|》|“|”|‘|’|：|，|。|、|；|·|「|」", '', heading)
	heading = re.sub(r"\s", '-', heading.lower())
	return "%s- [%s](#%s)"%((n-1)*'\t', new_heading, heading)

def gen_toc(file_name, start_line):
	lines = []
	with open(file_name, 'r') as raw_file:
		lines = raw_file.readlines()
	# backup file
	backup_time = time.strftime("%Y%m%d%H%M%S")
	backup_name = '_'.join((file_name.split(".")[0], backup_time, "bak.md"))
	shutil.copy(file_name,backup_name)
	print "Old file was backed up!"
	# find all headings
	headings = [line.strip() for line in lines if re.match(r"^#+", line)]
	# process headings
	toc_headings = [process_headings(h) for h in headings]
	lines.insert(int(start_line)-1, "\n" + LINK + "  \n".join(toc_headings) + "  \n\n")
	with open(file_name, 'w') as new_file:
		new_file.write(''.join(lines) + "  \n")
	print "New file with TOC was created successfully!"
		 
if __name__ == '__main__':
	arg_len = len(sys.argv)
	if 2 == arg_len:
		file_name = sys.argv[1]
		start_line = 1
		gen_toc(file_name, start_line)
	elif 3 == arg_len:
		file_name = sys.argv[1]
		start_line = sys.argv[2]
		gen_toc(file_name, start_line)
	else :
		print """	
		Wrong arguments!

		usage:
		./gen_TOC.py target_file(.md) [start line]
		"""
